name: Submodules Sync

on:
  workflow_dispatch:

jobs:
  sync:
    name: Submodules Sync
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Git Sumbodule Update
      run: git submodule update --init --remote --recursive

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.9.1
      with:
        token: ${{ secrets.PAT }}
        commit-message: Update submodules
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: update/submodules
        delete-branch: true
        title: 'update: submodules'
